/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ss1316.battleship;

import java.io.*;

public class App {
    private final TextPlayer player1, player2;

    public App(TextPlayer player1, TextPlayer player2) {
        this.player1 = player1;
        this.player2 = player2;
    }

    public void doPlacementPhase() throws IOException {
        // player1.doPlacementPhase();
        // player2.doPlacementPhase();
        player1.checkBeforeDoPlacement();
        player2.checkBeforeDoPlacement();
    }

    public void doAttackingPhase() throws IOException {
        TextPlayer curTurnPlayer = player1;
        while (true) {
            TextPlayer otherPlayer = curTurnPlayer == player1 ? player2 : player1;
            curTurnPlayer.playOneTurn(otherPlayer.getName(), otherPlayer.getView());
            if (otherPlayer.isLost()) {
                System.out.println("Player " + curTurnPlayer.getName() + " is WINNER!");
                break;
            }
            curTurnPlayer = otherPlayer;
        }
    }

    private static String choosePlayType(String name, BufferedReader input, PrintStream out) throws IOException {
        String prompt = "Player "+ name + ": please choose play type:\n" 
        + "H human\n"
        + "C computer\n";
        while (true) {
            out.print(prompt);
            String s = input.readLine();
            s = s.toUpperCase();
            if (s.equals("H") || s.equals("C")) {
                return s;
            } else {
                out.println("Invalid input!");
                continue;
            }
        }
    }

    public static void main(String[] args) throws IOException {
        Board<Character> b1 = new BattleShipBoard<Character>(10, 20,'X');
        Board<Character> b2 = new BattleShipBoard<Character>(10, 20,'X');
        BufferedReader input = new BufferedReader(new InputStreamReader(System.in));
        // V1ShipFactory factory = new V1ShipFactory();
        V2ShipFactory factory = new V2ShipFactory();
        // TextPlayer p1 = new TextPlayer("A", b1, input, System.out, factory);
        // TextPlayer p2 = new TextPlayer("B", b2, input, System.out, factory);
       

        String s1 = choosePlayType("A", input, System.out);
        String s2 = choosePlayType("B", input, System.out);
        TextPlayer p1, p2;
        boolean t1 = s1.equals("H");
        boolean t2 = s2.equals("H");
        // if (s1.equals("H")) {
            p1 = new TextPlayer("A", b1, input, System.out, factory, t1);
        // } else {
        //     p1 = new TextPlayer("A", b1, input, System.out, factory, false);
        // }
        // if (s2. equals("H")) {
            p2 = new TextPlayer("B", b2, input, System.out, factory, t2);
        // } else {
        //     p2 = new TextPlayer("B", b2, input, System.out, factory, false);
        // }
        App app = new App(p1, p2);
        app.doPlacementPhase();
        app.doAttackingPhase();
    }
}
